# Generated by Django 3.2.3 on 2023-11-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20231123_1717'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favouriterecipe',
            name='user_recipe_fav',
        ),
        migrations.AddConstraint(
            model_name='favouriterecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='favourite_recipe'),
        ),
    ]
